# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LiveorFriends.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
import traceback

dev_auth = [0, ""]  # Developer ID and Auth Key

name = ""


class Ui_LiveMatchorFriendsWindow(object):
    # when window is created, get data from past window
    def __init__(self, x, y, z):
        global name, dev_auth
        # set the name
        name = x
        # current dev id
        dev_auth[0] = y
        # current auth key
        dev_auth[1] = z

    def setupUi(self, LiveMatchorFriendsWindow):
        LiveMatchorFriendsWindow.setObjectName("LiveMatchorFriendsWindow")
        LiveMatchorFriendsWindow.setFixedSize(800, 600)
        LiveMatchorFriendsWindow.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(LiveMatchorFriendsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 150, 280, 100))
        self.label.setStyleSheet("color: #cccccc;")
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.friends_button = QtWidgets.QPushButton(self.centralwidget)
        self.friends_button.setGeometry(QtCore.QRect(440, 280, 175, 80))
        self.friends_button.setStyleSheet("color: black; background-color: grey;")
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.friends_button.setFont(font)
        self.friends_button.setObjectName("friends_button")
        self.livematch_button = QtWidgets.QPushButton(self.centralwidget)
        self.livematch_button.setGeometry(QtCore.QRect(185, 280, 175, 80))
        self.livematch_button.setStyleSheet("color: black; background-color: grey;")
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.livematch_button.setFont(font)
        self.livematch_button.setObjectName("livematch_button")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 81, 28))
        self.backButton.setStyleSheet("color: black; background-color: grey;")
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        LiveMatchorFriendsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LiveMatchorFriendsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        LiveMatchorFriendsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LiveMatchorFriendsWindow)
        self.statusbar.setObjectName("statusbar")
        LiveMatchorFriendsWindow.setStatusBar(self.statusbar)

        self.backButton.clicked.connect(self.backWindow)
        self.backButton.clicked.connect(LiveMatchorFriendsWindow.close)
        self.backButton.setAutoDefault(True)

        self.livematch_button.clicked.connect(self.openLive_Match)
        self.livematch_button.clicked.connect(LiveMatchorFriendsWindow.close)
        self.livematch_button.setAutoDefault(True)

        # self.friends_button.clicked.connect(self.openFriends_List)
        # self.friends_button.clicked.connect(LiveMatchorFriendsWindow.close)

        self.retranslateUi(LiveMatchorFriendsWindow)
        QtCore.QMetaObject.connectSlotsByName(LiveMatchorFriendsWindow)

    '''def openFriends_List(self):
        global name, dev_auth, logfile
        # grab Ui of FriendsList
        from FriendsList import Ui_FriendsList
        try:
            #create window
            self.window = QtWidgets.QMainWindow()
            # grabs ui of friendslist window
            self.ui = Ui_FriendsList(name, dev_auth[0], dev_auth[1])
            # set up the ui of FriendsList
            self.ui.setupUi(self.window)
            # set up title
            self.window.setWindowTitle("Paladins Live Beta 1.0")
            # display new window
            self.window.show()
        except Exception:
            username = os.getlogin()
            with open(f"C:\\Users\\{username}\\Desktop\\PaladinsLiveBeta-Error.log", "a") as logfile:
                traceback.print_exc(file=logfile)
            raise'''

    def openLive_Match(self):
        global name, dev_auth, logfile
        # grab Ui of LiveMatch
        from LiveMatch import Ui_LiveMatchWindow
        try:
            # create window
            self.window = QtWidgets.QMainWindow()
            # grabs ui of second window
            self.ui = Ui_LiveMatchWindow(name, dev_auth[0], dev_auth[1])
            # sets up the second ui in the new window
            self.ui.setupUi(self.window)
            # set title
            self.window.setWindowTitle("Paladins Live Beta 1.0")
            # display new window
            self.window.show()
        except Exception:
            username = os.getlogin()
            with open(f"C:\\Users\\{username}\\Desktop\\PaladinsLiveBeta-Error.log", "a") as logfile:
                traceback.print_exc(file=logfile)
            raise


    def backWindow(self):
        global logfile, dev_auth
        # grab Ui of MainScreen
        from MainScreen import Ui_MainWindow
        try:
            # create window
            self.window = QtWidgets.QMainWindow()
            # grabs ui of second window
            self.ui = Ui_MainWindow(dev_auth[0], dev_auth[1])
            # sets up the second ui in the new window
            self.ui.setupUi(self.window)
            # set title
            self.window.setWindowTitle("Paladins Live Beta 1.0")
            # display new window
            self.window.show()
        except Exception:
            username = os.getlogin()
            with open(f"C:\\Users\\{username}\\Desktop\\PaladinsLiveBeta-Error.log", "a") as logfile:
                traceback.print_exc(file=logfile)
            raise

    def retranslateUi(self, LiveMatchorFriendsWindow):
        _translate = QtCore.QCoreApplication.translate
        LiveMatchorFriendsWindow.setWindowTitle(_translate("LiveMatchorFriendsWindow", "MainWindow"))
        self.label.setText(_translate("LiveMatchorFriendsWindow", "Choose an option"))
        self.label.adjustSize()
        self.label.setGeometry(QtCore.QRect((LiveMatchorFriendsWindow.width() - self.label.width())//2, 150, 280, 100))
        self.label.adjustSize()
        self.friends_button.setText(_translate("LiveMatchorFriendsWindow", "Friends List"))
        self.livematch_button.setText(_translate("LiveMatchorFriendsWindow", "Live Match"))
        self.backButton.setText(_translate("LiveMatchorFriendsWindow", "Esc"))
        self.backButton.setShortcut(_translate("LiveMatchorFriendsWindow", "Esc"))
